# Generated by Django 4.1.5 on 2023-01-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_food_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
    ]
